POST http://localhost:5000/api/register HTTP/1/1
Content-Type: application/json 


{
  "username": "user",
  "email": "user@gmail.com",
  "password": "user"
}

###

POST http://localhost:5000/api/login HTTP/1/1
Content-Type: application/json 


{
  "username": "user",
  "password": "user"
}

###

PUT http://localhost:5000/api/user/61875dda3f1f2b099a526a2d HTTP/1/1
Content-Type: application/json 


{
  "username": "user edit",
  "password": "user",
  "accessToken": "token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODc1ZGRhM2YxZjJiMDk5YTUyNmEyZCIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzYyOTkwMzMsImV4cCI6MTYzNjU1ODIzM30.5xX6uaUOBj6RQZps-7mfTrf6jfXgHgSG-REPxAN1i48"
}